name: yandex_sirius
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  freezed: ^2.4.7
  get_it: ^7.6.7
  google_fonts: ^6.2.0
  isar: ^3.1.0+1
  logger: ^2.2.0
  surf_lint_rules: ^1.0.0
  formz: ^0.6.1
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_analytics: ^10.8.10
  firebase_auth: ^4.17.9
  cloud_firestore:
  image_picker: ^1.0.7
  intl: any
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  mask_text_input_formatter: ^2.9.0
  firebase_storage: ^11.6.11

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
