name: Dart

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  analyze_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze --fatal-infos
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup dart
        uses: dart-lang/setup-dart@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Firebase config
        run: curl -sL https://firebase.tools | bash

      - run: dart pub global activate flutterfire_cli

      - run: export PATH="$PATH":"$HOME/.pub-cache/bin"
      - run: flutterfire configure --token ${{secrets.FIREBASE_TOKEN}}
            --project="yandex_sirius"
            --platforms="android"
            --android-package-name="com.example.yandex_sirius"
            --yes

      - name: Build Apk
        run: flutter build apk --debug --flavor development --target lib/main_development.dart